apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-backend
  namespace: go-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-backend
  template:
    metadata:
      labels:
        app: redis-backend
    spec:
      containers:
      - name: redis-backend
        image: your-dockerhub-username/redis-backend:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: redis-backend
  namespace: go-apps
spec:
  selector:
    app: redis-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
