name: CI for Counter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Counter Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Install Dependencies
      run: go mod tidy

    - name: Build the Application
      run: go build -o counter_backend ./apps/counter_backend/main.go

    - name: Run Tests
      run: go test ./apps/counter_backend/...

    - name: Verify the Application Runs
      run: |
        ./counter_backend &
        sleep 5
        curl -v http://localhost:8080/ || exit 1

    - name: Cleanup
      run: kill $(jobs -p) || true
