name: CI for Counter Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Counter Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set Working Directory to Counter Backend
      run: cd apps/counter_backend

    - name: Install Dependencies
      working-directory: ./apps/counter_backend
      run: go mod tidy

    - name: Build the Application
      working-directory: ./apps/counter_backend
      run: go build -o counter_backend main.go

    - name: Run Tests
      working-directory: ./apps/counter_backend
      run: go test ./...

    - name: Verify the Application Runs
      working-directory: ./apps/counter_backend
      run: |
        ./counter_backend &
        sleep 5
        curl -v http://localhost:8080/ || exit 1

    - name: Cleanup
      run: kill $(jobs -p) || true
